import { controlPlaneContext } from './context.mjs';

export { createControlPlaneContext, controlPlaneContext } from './context.mjs';
export { createControlPlaneStore, controlPlaneStore } from './store.mjs';
export { createAgentActionRequestRepository } from './repositories/agent-action-request-repo.mjs';
export { createAuditRepository } from './repositories/audit-repo.mjs';
export { createBacktestRunRepository } from './repositories/backtest-run-repo.mjs';
export { createCycleRepository } from './repositories/cycle-repo.mjs';
export { createExecutionPlanRepository } from './repositories/execution-plan-repo.mjs';
export { createExecutionRuntimeRepository } from './repositories/execution-runtime-repo.mjs';
export { createIncidentRepository } from './repositories/incident-repo.mjs';
export { createMarketProviderRepository } from './repositories/market-provider-repo.mjs';
export { createOperatorActionRepository } from './repositories/operator-action-repo.mjs';
export { createNotificationRepository } from './repositories/notification-repo.mjs';
export { createResearchSummaryRepository } from './repositories/research-summary-repo.mjs';
export { createRiskRepository } from './repositories/risk-repo.mjs';
export { createSchedulerRepository } from './repositories/scheduler-repo.mjs';
export { createStrategyRepository } from './repositories/strategy-repo.mjs';
export { createUserAccountRepository } from './repositories/user-account-repo.mjs';
export { createWorkflowRepository } from './repositories/workflow-repo.mjs';

export const listAuditRecords = (...args) => controlPlaneContext.audit.listAuditRecords(...args);
export const appendAuditRecord = (...args) => controlPlaneContext.audit.appendAuditRecord(...args);
export const listAgentActionRequests = (...args) => controlPlaneContext.agentActionRequests.listAgentActionRequests(...args);
export const getAgentActionRequest = (...args) => controlPlaneContext.agentActionRequests.getAgentActionRequest(...args);
export const appendAgentActionRequest = (...args) => controlPlaneContext.agentActionRequests.appendAgentActionRequest(...args);
export const updateAgentActionRequest = (...args) => controlPlaneContext.agentActionRequests.updateAgentActionRequest(...args);
export const listBacktestRuns = (...args) => controlPlaneContext.backtestRuns.listBacktestRuns(...args);
export const getBacktestRun = (...args) => controlPlaneContext.backtestRuns.getBacktestRun(...args);
export const findBacktestRunByWorkflowRunId = (...args) => controlPlaneContext.backtestRuns.findBacktestRunByWorkflowRunId(...args);
export const appendBacktestRun = (...args) => controlPlaneContext.backtestRuns.appendBacktestRun(...args);
export const updateBacktestRun = (...args) => controlPlaneContext.backtestRuns.updateBacktestRun(...args);
export const listCycleRecords = (...args) => controlPlaneContext.cycles.listCycleRecords(...args);
export const appendCycleRecord = (...args) => controlPlaneContext.cycles.appendCycleRecord(...args);
export const listOperatorActions = (...args) => controlPlaneContext.operatorActions.listOperatorActions(...args);
export const appendOperatorAction = (...args) => controlPlaneContext.operatorActions.appendOperatorAction(...args);
export const listExecutionPlans = (...args) => controlPlaneContext.executionPlans.listExecutionPlans(...args);
export const getExecutionPlan = (...args) => controlPlaneContext.executionPlans.getExecutionPlan(...args);
export const findExecutionPlanByWorkflowRunId = (...args) => controlPlaneContext.executionPlans.findExecutionPlanByWorkflowRunId(...args);
export const appendExecutionPlan = (...args) => controlPlaneContext.executionPlans.appendExecutionPlan(...args);
export const updateExecutionPlan = (...args) => controlPlaneContext.executionPlans.updateExecutionPlan(...args);
export const listExecutionRuntimeEvents = (...args) => controlPlaneContext.executionRuntime.listExecutionRuntimeEvents(...args);
export const appendExecutionRuntimeEvent = (...args) => controlPlaneContext.executionRuntime.appendExecutionRuntimeEvent(...args);
export const listBrokerAccountSnapshots = (...args) => controlPlaneContext.executionRuntime.listBrokerAccountSnapshots(...args);
export const appendBrokerAccountSnapshot = (...args) => controlPlaneContext.executionRuntime.appendBrokerAccountSnapshot(...args);
export const listIncidents = (...args) => controlPlaneContext.incidents.listIncidents(...args);
export const getIncident = (...args) => controlPlaneContext.incidents.getIncident(...args);
export const listIncidentNotes = (...args) => controlPlaneContext.incidents.listIncidentNotes(...args);
export const appendIncident = (...args) => controlPlaneContext.incidents.appendIncident(...args);
export const updateIncident = (...args) => controlPlaneContext.incidents.updateIncident(...args);
export const appendIncidentNote = (...args) => controlPlaneContext.incidents.appendIncidentNote(...args);
export const getMarketProviderStatus = (...args) => controlPlaneContext.marketProviders.getMarketProviderStatus(...args);
export const updateMarketProviderStatus = (...args) => controlPlaneContext.marketProviders.updateMarketProviderStatus(...args);
export const listNotifications = (...args) => controlPlaneContext.notifications.listNotifications(...args);
export const appendNotification = (...args) => controlPlaneContext.notifications.appendNotification(...args);
export const enqueueNotification = (...args) => controlPlaneContext.notifications.enqueueNotification(...args);
export const listNotificationJobs = (...args) => controlPlaneContext.notifications.listNotificationJobs(...args);
export const dispatchPendingNotifications = (...args) => controlPlaneContext.notifications.dispatchPendingNotifications(...args);
export const getResearchSummary = (...args) => controlPlaneContext.researchSummary.getResearchSummary(...args);
export const updateResearchSummary = (...args) => controlPlaneContext.researchSummary.updateResearchSummary(...args);
export const listRiskEvents = (...args) => controlPlaneContext.risk.listRiskEvents(...args);
export const appendRiskEvent = (...args) => controlPlaneContext.risk.appendRiskEvent(...args);
export const enqueueRiskScan = (...args) => controlPlaneContext.risk.enqueueRiskScan(...args);
export const listRiskScanJobs = (...args) => controlPlaneContext.risk.listRiskScanJobs(...args);
export const dispatchPendingRiskScans = (...args) => controlPlaneContext.risk.dispatchPendingRiskScans(...args);
export const listSchedulerTicks = (...args) => controlPlaneContext.scheduler.listSchedulerTicks(...args);
export const recordSchedulerTick = (...args) => controlPlaneContext.scheduler.recordSchedulerTick(...args);
export const listStrategies = (...args) => controlPlaneContext.strategyCatalog.listStrategies(...args);
export const getStrategy = (...args) => controlPlaneContext.strategyCatalog.getStrategy(...args);
export const upsertStrategy = (...args) => controlPlaneContext.strategyCatalog.upsertStrategy(...args);
export const getUserAccount = (...args) => controlPlaneContext.userAccount.getUserAccount(...args);
export const getUserProfile = (...args) => controlPlaneContext.userAccount.getUserProfile(...args);
export const updateUserProfile = (...args) => controlPlaneContext.userAccount.updateUserProfile(...args);
export const getUserPreferences = (...args) => controlPlaneContext.userAccount.getUserPreferences(...args);
export const updateUserPreferences = (...args) => controlPlaneContext.userAccount.updateUserPreferences(...args);
export const listBrokerBindings = (...args) => controlPlaneContext.userAccount.listBrokerBindings(...args);
export const upsertBrokerBinding = (...args) => controlPlaneContext.userAccount.upsertBrokerBinding(...args);
export const listWorkflowRuns = (...args) => controlPlaneContext.workflows.listWorkflowRuns(...args);
export const getWorkflowRun = (...args) => controlPlaneContext.workflows.getWorkflowRun(...args);
export const appendWorkflowRun = (...args) => controlPlaneContext.workflows.appendWorkflowRun(...args);
export const updateWorkflowRun = (...args) => controlPlaneContext.workflows.updateWorkflowRun(...args);
export const releaseScheduledWorkflowRuns = (...args) => controlPlaneContext.workflows.releaseScheduledWorkflowRuns(...args);
export const claimQueuedWorkflowRuns = (...args) => controlPlaneContext.workflows.claimQueuedWorkflowRuns(...args);
