import { getBacktestSummary } from '../../backtest/services/summary-service.mjs';
import { listBacktestRuns } from '../../backtest/services/runs-service.mjs';
import { listExecutionPlans } from '../../execution/services/query-service.mjs';
import { listRiskEvents } from '../../risk/services/feed-service.mjs';
import { listStrategyCatalog } from '../../strategy/services/catalog-service.mjs';

const AGENT_TOOLS = [
  {
    name: 'strategy.catalog.list',
    category: 'strategy',
    description: 'Read the current strategy catalog, scores, and promotion stages.',
    access: 'read',
  },
  {
    name: 'backtest.summary.get',
    category: 'backtest',
    description: 'Read the aggregated backtest center summary.',
    access: 'read',
  },
  {
    name: 'backtest.runs.list',
    category: 'backtest',
    description: 'Read recent backtest runs and their statuses.',
    access: 'read',
  },
  {
    name: 'risk.events.list',
    category: 'risk',
    description: 'Read recent risk events generated by the control plane.',
    access: 'read',
  },
  {
    name: 'execution.plans.list',
    category: 'execution',
    description: 'Read persisted execution plans and their current review state.',
    access: 'read',
  },
];

export function listAgentTools() {
  return {
    ok: true,
    tools: AGENT_TOOLS,
  };
}

function executeStrategyCatalogTool() {
  const snapshot = listStrategyCatalog();
  return {
    ok: true,
    tool: 'strategy.catalog.list',
    summary: `Loaded ${snapshot.strategies.length} strategy catalog entries.`,
    data: {
      asOf: snapshot.asOf,
      strategies: snapshot.strategies,
    },
  };
}

function executeBacktestSummaryTool() {
  const snapshot = getBacktestSummary();
  return {
    ok: true,
    tool: 'backtest.summary.get',
    summary: `Backtest center has ${snapshot.completedRuns} completed runs and ${snapshot.reviewQueue} items in review.`,
    data: snapshot,
  };
}

function executeBacktestRunsTool(args = {}) {
  const snapshot = listBacktestRuns();
  const status = args.status || '';
  const runs = status
    ? snapshot.runs.filter((item) => item.status === status)
    : snapshot.runs;
  return {
    ok: true,
    tool: 'backtest.runs.list',
    summary: `Loaded ${runs.length} backtest runs${status ? ` with status ${status}` : ''}.`,
    data: {
      asOf: snapshot.asOf,
      runs,
    },
  };
}

function executeRiskEventsTool(args = {}) {
  const limit = Number.isFinite(args.limit) ? args.limit : 10;
  const events = listRiskEvents(limit);
  return {
    ok: true,
    tool: 'risk.events.list',
    summary: `Loaded ${events.length} risk events.`,
    data: {
      events,
    },
  };
}

function executeExecutionPlansTool(args = {}) {
  const limit = Number.isFinite(args.limit) ? args.limit : 10;
  const plans = listExecutionPlans(limit);
  return {
    ok: true,
    tool: 'execution.plans.list',
    summary: `Loaded ${plans.length} execution plans.`,
    data: {
      plans,
    },
  };
}

export function executeAgentTool(payload = {}) {
  const tool = payload.tool || '';
  const args = payload.args || {};

  switch (tool) {
    case 'strategy.catalog.list':
      return executeStrategyCatalogTool();
    case 'backtest.summary.get':
      return executeBacktestSummaryTool();
    case 'backtest.runs.list':
      return executeBacktestRunsTool(args);
    case 'risk.events.list':
      return executeRiskEventsTool(args);
    case 'execution.plans.list':
      return executeExecutionPlansTool(args);
    default:
      return {
        ok: false,
        tool,
        summary: `Tool ${tool || 'unknown'} is not allowed for Agent access.`,
        data: {},
      };
  }
}
